export default function LearningstatementContent() {

    // NOTE: you have to have a div wrapping everything in the return statement!
    return (
        <div className="px-md-5">  
            <img className="py-3 w-100" src='img/honors-project/artifact-images/learningstatement-collage.PNG' alt='clear glasses with a sunset in the lenses' />
            <p className="py-2">Throughout my academic journey, I have grown into a designer shaping a more inclusive and sustainable future. My courses and experiences as an Industrial Design major in the Interdisciplinary Honors program have allowed me to explore design across a wide range of fields, ultimately expanding my knowledge on how design is a tool to shift culture and improve lives. Venturing into museology, ethnomusicology, exhibit design, interior design, product design, material science, and computer science, I learned how to embrace my interdisciplinary nature, often seeing connections between seemingly unrelated fields. More than just technical skills and experience, I gained a deeper understanding of my positionality within the realm of design and gained confidence navigating a male dominated field as a queer woman.</p>
            <p className="py-2">My education, formed within and outside the classroom, became a rich tapestry woven with diverse passions, unraveling the intricate relationship between products and the world that envelops them. I learned about the complex social structures that impact who gets to design products, what products are made, and their widespread impacts. I grew to view sustainability holistically, focusing not only on the impact of design on our environment, but also the impact of design on our social, physical, and mental wellbeing as both individuals and a collective.</p>
            <p className="py-2">My understanding of design as an instrument for social change and engagement caused me to explore how I could apply my creative abilities as a form of community engagement on campus. Working within teams throughout clubs across campuses showed me the ways in which design bridges disciplines. These projects not only brought me closer to my peers, but it also showed me the power of collaboration.My interest in design and its relation to the community naturally extended to the effects of product manufacturing. I continue to think about manufacturing processes that eliminate or reduce waste. I’m continuously exploring new materials like spent coffee grounds collected from local cafes to create a concrete-like material, recycled paper pulp, biorubber, and natural dyes.</p>
            <p className="py-2">Along with my passion in product design, I also gained a passion for the design of museum, library, and archival spaces for their intersection of design and technology and for their function as a third place within the community. Through Honors courses such as Solving Problems in Museum Spaces, Looted? Ethnomusicology, Archives & Colonial Legacies, and Seattle Sounds, I studied the importance of exhibit design in creating engaging experiences. I learned to be critical about the power dynamics involved in exhibit creation, how to use exhibits as a platform to amplify voices, and question what we know to be true about artifacts in a collection. Through a study abroad on innovation and decolonization within museums, libraries, and archives in the Netherlands, I was able to grow my knowledge of decolonization within art institutions, including the complexities of repatriation and institutional initiatives to build inclusive use of language surrounding artworks. Working on museum related projects reaffirmed my role as a designer in utilizing exhibitions as a way to engage the public with important topics. Whether highlighting community resiliency through the pandemic, or generating conversations related to archival control and access, I learned that exhibits are a powerful way to start conversations from a place of open mindedness.</p>
            <p className="py-2">Equipped with a multifaceted understanding of design's impact and technical abilities, I am poised for a future where I can contribute meaningfully to the ever-evolving world of design. My experience has equipped me to be a leader for sustainable and inclusive design, embrace innovation, seek understanding of diverse communities, and problem solve with optimism.</p>
        </div>
    )
}