/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 aboutmefigure-02.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function AboutMeFigure02(props) {
  const { nodes, materials } = useGLTF('/img/aboutmefigure-02.gltf')
  // console.log(nodes, materials)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[109.845, 3586.784, -108.007]} scale={0.05}>
          <group scale={0.05}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh geometry={nodes.Female_body_reference_2.geometry} material={materials.Eyes_bsd} />
              <mesh geometry={nodes.Female_body_reference_3.geometry} material={materials.Body_bsd} />
            </group>
            <mesh geometry={nodes.Cube_2.geometry} material={materials['Hard Shiny Plastic White #1']} position={[-70.402, 1633.78, 115.169]} rotation={[-Math.PI / 2, 0, 0]} scale={[222.001, 225.866, 594.384]} />
            <mesh geometry={nodes.Cube001_2.geometry} material={materials['Hard Shiny Plastic White #1']} position={[-70.43, 2053.61, 243.444]} rotation={[-Math.PI / 2, 0, 0]} scale={[318.653, 324.2, 472.223]} />
            <mesh geometry={nodes.Cube002_2.geometry} material={materials['Clear Shiny Plastic White #8']} position={[-69.676, -120.514, 192.476]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-1840.63, 929.262, 3494.15]} />
            <mesh geometry={nodes.Cube003_2.geometry} material={materials['craft paper #2']} position={[-69.676, 4108.64, 192.476]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-1840.63, 83.496, 754.169]} />
            <mesh geometry={nodes['W-Skirt_25_obj_2'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[0, -3485.64, 0]} scale={34.396} />
            <group position={[0, -3337.88, -57.999]} rotation={[0.065, -0.005, 0.013]} scale={32.594}>
              <mesh geometry={nodes['uploads-files-4679006-shirtdressOBJ(1)_2'].geometry} material={materials['Material.001']} />
              <mesh geometry={nodes['uploads-files-4679006-shirtdressOBJ(1)_3'].geometry} material={materials.Material4584} />
              <mesh geometry={nodes['uploads-files-4679006-shirtdressOBJ(1)_4'].geometry} material={materials['Hard Shiny Plastic Green #1']} />
              <mesh geometry={nodes['uploads-files-4679006-shirtdressOBJ(1)_5'].geometry} material={materials.Material4569} />
            </group>
            <mesh geometry={nodes.bottom_design_2_Cube004_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.bottom_pad__Cube003_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.bottom_pad_DESIGN_Cube013_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.botttom_design_1_Cube002_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_001_Cube011_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_002_Cube012_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_003_Cube014_2.geometry} material={materials.back_band} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_004_Cube015_2.geometry} material={materials.upper_strap} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_005_Cube016_2.geometry} material={materials.lower_black_} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_006_Cube006_2.geometry} material={materials['inner_shoes.001']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_007_Cube010_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_008_Cube017_2.geometry} material={materials.upper_strap} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes__Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <group position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]}>
              <mesh geometry={nodes.middle_band__Cube005_2.geometry} material={materials['Hard Shiny Plastic Green #1']} />
              <mesh geometry={nodes.middle_band__Cube005_3.geometry} material={materials['Hard Shiny Plastic Green #1']} />
            </group>
            <mesh geometry={nodes.side_design_Cube009_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.STITCHS_2_Cube019_2.geometry} material={materials.lower_black_} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.thired_Cube018_2.geometry} material={materials.lower_black_} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.up_strap_1_Cube007_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.up_strap_2_Cube008_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[403.603, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.up_strap_2_Cube001_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.up_strap_1_Cube001_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.thired_Cube001_2.geometry} material={materials['lower_black_.001']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.STITCHS_2_Cube001_2.geometry} material={materials['lower_black_.001']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.side_design_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <group position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]}>
              <mesh geometry={nodes.middle_band__Cube001_2.geometry} material={materials['Material.009']} />
              <mesh geometry={nodes.middle_band__Cube001_3.geometry} material={materials['Hard Shiny Plastic Green #1']} />
            </group>
            <mesh geometry={nodes.main_shoes__Cube002_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_008_Cube001_2.geometry} material={materials['upper_strap.001']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_007_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_006_Cube001_2.geometry} material={materials['inner_shoes.005']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_005_Cube001_2.geometry} material={materials['lower_black_.001']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_004_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_003_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_002_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.main_shoes_001_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.botttom_design_1_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.bottom_pad_DESIGN_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.bottom_pad__Cube001_2.geometry} material={materials['Hard Shiny Plastic Green #1']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes.bottom_design_2_Cube001_2.geometry} material={materials['Hard Shiny Plastic Blue #2']} position={[-509.292, -3108.95, 435.217]} rotation={[-0.119, -0.376, 0.106]} scale={[245.463, 245.462, 245.463]} />
            <mesh geometry={nodes['uploads-files-2846415-Hair_Fem_Bob_01_2'].geometry} material={materials['Hard Shiny Plastic Black #1']} position={[-69.793, 2090.13, 207.64]} rotation={[-0.247, 0.319, 0.04]} scale={[34.27, 35.106, 32.073]} />
            <mesh geometry={nodes.Female_body_reference003_2.geometry} material={materials['Hard Shiny Plastic White #1']} position={[-65.821, -3136.72, 149.435]} rotation={[-Math.PI / 2, 0, 0]} scale={3245.67} />
          </group>
        </group>
        <group position={[109.678, 3591.711, -106.748]} scale={0.009}>
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_1'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_2'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_3'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_4'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_5'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_6'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_7'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_8'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_9'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_10'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_11'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_12'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_13'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_14'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_15'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
          <mesh geometry={nodes['Sam-Does-Design-Glasses-2019_v2_16'].geometry} material={materials['Hard Shiny Plastic Black #3']} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={60.675} near={53.746} fov={39.598} position={[1.013, 35.913, -0.512]} rotation={[-0.051, -0.144, -0.007]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/img/aboutmefigure-02.gltf')
